-- PARA INDICAR CUAL BASE VOY A USAR
USE comercio;

-- para mostrar tablas que tiene la base
SHOW TABLES;

/* 
	SQL SERVER_ SELECT * FROM SYS.TABLES
	RACLE: SELECT * FROM ALL_TABLES
    
*/

-- para ver la definicion de una tabla
DESCRIBE clientes;

-- SQL SERVER: SP_HELT TABLA

SELECT * FROM clientes;

SELECT * FROM FACTURAS;

SELECT * FROM productos;

-------------------------------------------------
SELECT NOMBRE, APELLIDO, DNI, TELEFONO
FROM CLIENTES;

SELECT NOMBRE 	NOMBRE_PRODUCTO, MARCA 	DISEÑADOR, COLOR 	TONO, PRECIO, PRECIO * 0.80 AS con_iva
FROM PRODUCTOS;

SELECT concat(NOMBRE, ' ' ,APELLIDO) AS NOMBRE_COMPLETO
FROM CLIENTES;

SELECT *
FROM FACTURAS
WHERE FECHA = '2017-01-05';

/*
	FUNCIONES PARA VALORES DATE
	YEAR(F) -->> INT
    MONTH(F) -->> INT
    DAY(F) -->> INT
    NOW()
*/

SELECT LETRA, NUMERO, FECHA, year(FECHA), month(FECHA), day(FECHA)
FROM FACTURAS

SELECT *
FROM FACTURAS 
WHERE YEAR(FECHA) = 2017;

SELECT now();



/*
	FUNCIONES PARA DATOS CHAT-VARCHAR
    LEFT(CADENA, LONGITUD)
    RIGHT(CADENA, LONGITUD)
    SUBSTRING(CADENA, POSICION, LONG)
*/


SELECT APELLIDO, LEFT(APELLIDO,	2), RIGHT(APELLIDO, 2), SUBSTRING(APELLIDO, 2, 3)
FROM CLIENTES;



/* 
	PENTIENDE
    LINK
    
*/
		
